[package]
name = "deeper"
version = "0.1.0"
edition = "2021"

[dependencies]
typenum = { version = "1.16", features = ["const-generics"] }
num-traits = "0.2"
cust = "0.3"
cudnn = "1.3"
lazy_static = "1.4"
generic-array = "0.14"